// Renders the final Brevo-ready HTML in the SEPRI newsletter format.
// Structured content is generated by the AI (see newsletter-ai.server.ts) and
// rendered here using the visual language of the sample campaigns:
// overtitle kicker, big H1, intro, sections with emoji headings, bullet lists,
// grouped subsections and a highlighted "orientações" (guidelines) block when
// the source news carries clear instructions.

export interface NewsletterSubsection {
  heading: string;
  paragraph?: string;
  bullets?: string[];
}

export interface NewsletterSection {
  icon?: string; // emoji/icon character
  heading: string;
  paragraphs?: string[];
  bullets?: string[];
  subsections?: NewsletterSubsection[];
}

export interface NewsletterGuidelines {
  heading: string; // e.g. "Orientações práticas"
  intro?: string;
  items: string[]; // clear, imperative instructions
}

export interface NewsletterItemContent {
  overtitle?: string; // small-caps kicker, e.g. "NARIZ, PULMÕES E PRODUTIVIDADE"
  title: string; // H1
  subtitle?: string; // shown under the title
  intro_paragraphs: string[]; // 1-3 opening paragraphs
  sections: NewsletterSection[];
  guidelines?: NewsletterGuidelines;
  closing_paragraph?: string;
  source_name?: string;
  source_url?: string | null;
  published_at?: string | null;
}

export interface NewsletterDocument {
  subject: string;
  // Composite mode wraps multiple items with a shared intro.
  composite_intro?: {
    overtitle?: string;
    title: string;
    lead: string;
  };
  items: NewsletterItemContent[];
}

export interface NewsletterChrome {
  logoUrl: string;
  disclaimerHtml: string;
}

const TEAL = "#0f5e8f";
const INK = "#0f172a";
const MUTED = "#64748b";
const BODY = "#1e293b";
const BORDER = "#e2e8f0";
const HIGHLIGHT_BG = "#f0f7fb";
const HIGHLIGHT_BORDER = "#0f5e8f";

export function renderNewsletterHtml(doc: NewsletterDocument, chrome: NewsletterChrome): string {
  const itemsHtml = doc.items
    .map((item, idx) => renderItem(item, idx, doc.items.length > 1))
    .join("\n");

  const introHtml = doc.composite_intro
    ? `<tr><td style="padding:32px 32px 8px 32px;">
        ${
          doc.composite_intro.overtitle
            ? `<p style="font-size:12px;letter-spacing:2px;text-transform:uppercase;color:${TEAL};font-weight:700;margin:0 0 10px;">${esc(doc.composite_intro.overtitle)}</p>`
            : ""
        }
        <h1 style="font-size:26px;line-height:1.25;margin:0 0 12px;color:${INK};font-weight:800;">${esc(doc.composite_intro.title)}</h1>
        <p style="font-size:16px;line-height:1.6;color:${BODY};margin:0;">${esc(doc.composite_intro.lead)}</p>
      </td></tr>`
    : "";

  return `<!doctype html>
<html lang="pt">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(doc.subject)}</title>
</head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:Arial,Helvetica,sans-serif;color:${INK};">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:24px 0;">
  <tr><td align="center">
    <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(15,23,42,0.06);">
      <tr><td style="padding:24px 32px;border-bottom:1px solid ${BORDER};text-align:center;">
        <img src="${esc(chrome.logoUrl)}" alt="SEPRI Group" style="max-height:60px;height:auto;display:inline-block;" />
      </td></tr>
      ${introHtml}
      <tr><td style="padding:32px;">
        ${itemsHtml}
      </td></tr>
      <tr><td style="padding:20px 32px;background:#f1f5f9;border-top:1px solid ${BORDER};">
        ${chrome.disclaimerHtml}
      </td></tr>
    </table>
  </td></tr>
</table>
</body>
</html>`;
}

function renderItem(item: NewsletterItemContent, idx: number, isComposite: boolean): string {
  const separator =
    isComposite && idx > 0
      ? `<tr><td style="padding:0;"><hr style="border:none;border-top:1px solid ${BORDER};margin:32px 0;"/></td></tr>`
      : "";

  const overtitle = item.overtitle
    ? `<p style="font-size:12px;letter-spacing:2px;text-transform:uppercase;color:${TEAL};font-weight:700;margin:0 0 10px;">${esc(item.overtitle)}</p>`
    : "";

  const titleTag = isComposite ? "h2" : "h1";
  const titleSize = isComposite ? "22px" : "26px";
  const title = `<${titleTag} style="font-size:${titleSize};line-height:1.25;margin:0 0 8px;color:${INK};font-weight:800;">${esc(item.title)}</${titleTag}>`;

  const subtitle = item.subtitle
    ? `<p style="font-size:17px;line-height:1.45;color:${TEAL};font-weight:600;margin:0 0 16px;">${esc(item.subtitle)}</p>`
    : "";

  const publishedLine = item.published_at
    ? `<p style="font-size:13px;color:${MUTED};margin:0 0 16px;">Publicado em ${esc(
        new Date(item.published_at).toLocaleDateString("pt-PT"),
      )}${item.source_name ? ` · Fonte: ${esc(item.source_name)}` : ""}</p>`
    : item.source_name
    ? `<p style="font-size:13px;color:${MUTED};margin:0 0 16px;">Fonte: ${esc(item.source_name)}</p>`
    : "";

  const intro = (item.intro_paragraphs ?? [])
    .map(
      (p) =>
        `<p style="font-size:15px;line-height:1.7;color:${BODY};margin:0 0 14px;">${esc(p)}</p>`,
    )
    .join("\n");

  const sections = (item.sections ?? []).map(renderSection).join("\n");

  const guidelines = item.guidelines ? renderGuidelines(item.guidelines) : "";

  const closing = item.closing_paragraph
    ? `<p style="font-size:15px;line-height:1.7;color:${BODY};margin:24px 0 0;">${esc(item.closing_paragraph)}</p>`
    : "";

  const sourceLink = item.source_url
    ? `<p style="font-size:13px;margin:24px 0 0;"><a href="${esc(item.source_url)}" style="color:${TEAL};text-decoration:underline;">Ler na fonte original →</a></p>`
    : "";

  return `${separator}<tr><td style="padding:0;">
    ${overtitle}
    ${title}
    ${subtitle}
    ${publishedLine}
    ${intro}
    ${sections}
    ${guidelines}
    ${closing}
    ${sourceLink}
  </td></tr>`;
}

function renderSection(section: NewsletterSection): string {
  const heading = `<h3 style="font-size:18px;line-height:1.35;margin:24px 0 12px;color:${INK};font-weight:700;">${
    section.icon ? `<span style="margin-right:8px;">${esc(section.icon)}</span>` : ""
  }${esc(section.heading)}</h3>`;

  const paragraphs = (section.paragraphs ?? [])
    .map(
      (p) =>
        `<p style="font-size:15px;line-height:1.7;color:${BODY};margin:0 0 12px;">${esc(p)}</p>`,
    )
    .join("\n");

  const bullets = section.bullets && section.bullets.length
    ? renderBullets(section.bullets)
    : "";

  const subs = (section.subsections ?? [])
    .map((sub) => {
      const subBullets = sub.bullets && sub.bullets.length ? renderBullets(sub.bullets) : "";
      const subPara = sub.paragraph
        ? `<p style="font-size:15px;line-height:1.7;color:${BODY};margin:0 0 8px;">${esc(sub.paragraph)}</p>`
        : "";
      return `<div style="margin:12px 0 4px;">
        <p style="font-size:15px;line-height:1.5;color:${INK};font-weight:700;margin:0 0 6px;">${esc(sub.heading)}</p>
        ${subPara}
        ${subBullets}
      </div>`;
    })
    .join("\n");

  return `${heading}${paragraphs}${bullets}${subs}`;
}

function renderBullets(items: string[]): string {
  const li = items
    .map(
      (b) =>
        `<li style="font-size:15px;line-height:1.65;color:${BODY};margin:0 0 6px;">${esc(b)}</li>`,
    )
    .join("");
  return `<ul style="margin:0 0 14px 0;padding-left:22px;">${li}</ul>`;
}

function renderGuidelines(g: NewsletterGuidelines): string {
  const intro = g.intro
    ? `<p style="font-size:15px;line-height:1.65;color:${BODY};margin:0 0 10px;">${esc(g.intro)}</p>`
    : "";
  const items = g.items
    .map(
      (it) =>
        `<li style="font-size:15px;line-height:1.65;color:${INK};margin:0 0 8px;padding-left:6px;"><span style="color:${TEAL};font-weight:700;margin-right:6px;">✓</span>${esc(it)}</li>`,
    )
    .join("");
  return `<div style="margin:24px 0 8px;padding:20px 22px;background:${HIGHLIGHT_BG};border-left:4px solid ${HIGHLIGHT_BORDER};border-radius:6px;">
    <p style="font-size:12px;letter-spacing:2px;text-transform:uppercase;color:${TEAL};font-weight:700;margin:0 0 8px;">Orientações</p>
    <h4 style="font-size:17px;line-height:1.35;margin:0 0 10px;color:${INK};font-weight:800;">${esc(g.heading)}</h4>
    ${intro}
    <ul style="margin:0;padding:0;list-style:none;">${items}</ul>
  </div>`;
}

function esc(s: string): string {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
