/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSourcesRouteImport } from './routes/_app/sources'
import { Route as AppNewslettersRouteImport } from './routes/_app/newsletters'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppConfigRouteImport } from './routes/_app/config'
import { Route as ApiPublicRejectRouteImport } from './routes/api/public/reject'
import { Route as ApiPublicCronScanRouteImport } from './routes/api/public/cron-scan'
import { Route as ApiPublicApproveRouteImport } from './routes/api/public/approve'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNewslettersRoute = AppNewslettersRouteImport.update({
  id: '/newsletters',
  path: '/newsletters',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiPublicRejectRoute = ApiPublicRejectRouteImport.update({
  id: '/api/public/reject',
  path: '/api/public/reject',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronScanRoute = ApiPublicCronScanRouteImport.update({
  id: '/api/public/cron-scan',
  path: '/api/public/cron-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApproveRoute = ApiPublicApproveRouteImport.update({
  id: '/api/public/approve',
  path: '/api/public/approve',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof AppConfigRoute
  '/history': typeof AppHistoryRoute
  '/inbox': typeof AppInboxRoute
  '/newsletters': typeof AppNewslettersRoute
  '/sources': typeof AppSourcesRoute
  '/api/public/approve': typeof ApiPublicApproveRoute
  '/api/public/cron-scan': typeof ApiPublicCronScanRoute
  '/api/public/reject': typeof ApiPublicRejectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof AppConfigRoute
  '/history': typeof AppHistoryRoute
  '/inbox': typeof AppInboxRoute
  '/newsletters': typeof AppNewslettersRoute
  '/sources': typeof AppSourcesRoute
  '/api/public/approve': typeof ApiPublicApproveRoute
  '/api/public/cron-scan': typeof ApiPublicCronScanRoute
  '/api/public/reject': typeof ApiPublicRejectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/config': typeof AppConfigRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/newsletters': typeof AppNewslettersRoute
  '/_app/sources': typeof AppSourcesRoute
  '/api/public/approve': typeof ApiPublicApproveRoute
  '/api/public/cron-scan': typeof ApiPublicCronScanRoute
  '/api/public/reject': typeof ApiPublicRejectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/history'
    | '/inbox'
    | '/newsletters'
    | '/sources'
    | '/api/public/approve'
    | '/api/public/cron-scan'
    | '/api/public/reject'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/history'
    | '/inbox'
    | '/newsletters'
    | '/sources'
    | '/api/public/approve'
    | '/api/public/cron-scan'
    | '/api/public/reject'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/config'
    | '/_app/history'
    | '/_app/inbox'
    | '/_app/newsletters'
    | '/_app/sources'
    | '/api/public/approve'
    | '/api/public/cron-scan'
    | '/api/public/reject'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiPublicApproveRoute: typeof ApiPublicApproveRoute
  ApiPublicCronScanRoute: typeof ApiPublicCronScanRoute
  ApiPublicRejectRoute: typeof ApiPublicRejectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/newsletters': {
      id: '/_app/newsletters'
      path: '/newsletters'
      fullPath: '/newsletters'
      preLoaderRoute: typeof AppNewslettersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/public/reject': {
      id: '/api/public/reject'
      path: '/api/public/reject'
      fullPath: '/api/public/reject'
      preLoaderRoute: typeof ApiPublicRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-scan': {
      id: '/api/public/cron-scan'
      path: '/api/public/cron-scan'
      fullPath: '/api/public/cron-scan'
      preLoaderRoute: typeof ApiPublicCronScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/approve': {
      id: '/api/public/approve'
      path: '/api/public/approve'
      fullPath: '/api/public/approve'
      preLoaderRoute: typeof ApiPublicApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppConfigRoute: typeof AppConfigRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppInboxRoute: typeof AppInboxRoute
  AppNewslettersRoute: typeof AppNewslettersRoute
  AppSourcesRoute: typeof AppSourcesRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppConfigRoute: AppConfigRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppInboxRoute: AppInboxRoute,
  AppNewslettersRoute: AppNewslettersRoute,
  AppSourcesRoute: AppSourcesRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiPublicApproveRoute: ApiPublicApproveRoute,
  ApiPublicCronScanRoute: ApiPublicCronScanRoute,
  ApiPublicRejectRoute: ApiPublicRejectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
